schemaVersion: 2.2.0
metadata:
  name: ansible-demo2
components:
  - name: tooling-container
    container:
      image: quay.io/mloriedo/ansible-creator-ee:latest
      #image: quay.io/acme_corp/creator-ee-test:latest
      #image: quay.io/podman/stable
      memoryRequest: 256M
      memoryLimit: 2Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
#commands:
#  - id: oc-install
#    exec:
#      commandLine: '/usr/local/bin/ansible-playbook ${PROJECT_SOURCE}/playbooks/install_oc.yml'
#      workingDir: ${PROJECT_SOURCE}
#      group:
#        kind: build
#        isDefault: true
#      component: tooling-container
#events:
#  postStart:
#    - "oc-install"
